/**
 * ## CLI for the the module.
 *
 *
 * @packageDocumentation
 */


 /**
  *
  */

import * as ocf      from './lib/ocf';
import * as fs       from 'fs';
import * as cConvert from './clib/convert';


/**
 * Main CLI entry
 *
 * The steps performed by the CLI are:
 *
 * 1. Get the book description by reading the JSON configuration file provided as a CL argument;
 * 2. Create the target book's OCF content (see [[convert_to_epub]]);
 * 3. Generate the final OCF file and store it at the file whose name is indicated in the JSON configuration file.
 *
 * @async
 * @throws any error generated by the steps above
 */
async function main() :Promise<void> {
    if (process.argv.length < 3) {
        console.log("Need an argument!")
    } else {
        try {
            const args = fs.readFileSync(process.argv[2], 'utf-8');
            const the_ebook     :ocf.OCF = await cConvert.create_epub(JSON.parse(args));
            const final_content :Buffer  = await the_ebook.get_content() as Buffer;
            fs.writeFileSync(the_ebook.name, final_content)
        } catch (e) {
            console.log(e);
        }
    }
}

main();
